### PR TITLE
Added jg_reject filter.

### PR DESCRIPTION
**Pull request by sagotch**
This page is very basic (it is work in progress), but let me introduce an online jingoo parser/interpreter: https://sagotch.github.io/try-jingoo/

I added this filter because my example dealing with the oldest person did not work without it :D

### CODE REVIEW

**Comment by tategakibunko** [comment]
Wow, playground is built by `js_of_ocaml`,  it's really interesting! 358KByte is a bit large but within acceptable size.

About `jg_reject`, it's okay, but could you add unit test to `test_runtime.ml`?

**Comment by sagotch** [comment]
I agree that filter would be better (except that it will be called the filter filter...). I think that we can have both. I'll add `filter`, some unit test and examples in cheatsheet.

**Comment by sagotch** [comment]
Defined both `filter` and `reject` filters, and added some test.

**Comment by tategakibunko** [comment]
Thank you!!

**Pull request merged**
