### PR TITLE
Added Tarray type

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thank for supporting!
Looks great but `Array.iter2` is since 4.03.0, and jingoo is expected to run since version 4.02.0.
Can you avoid using `Array.iter2`?

**Comment by sagotch** [comment]
Ok, `iter2` is very simple to copy, so I will add amend my commit with it.

But when you will be ready to drop support for 4.02, `Array.iter2` is likely to be faster (https://github.com/ocaml/ocaml/blob/trunk/stdlib/array.ml#L92) than homemade iter2 even if I do not know the difference between `get` and `unsafe_get`

**Comment by tategakibunko** [comment]
Thank you!!

Issues of `Array.iter2` are fixed. 

But `Array.exists` is also since `4.03.0`.

It seems that 2way iterator or scanning functions for `Array` are all since `4.03.0`.

`Array.iter2`, `Array.map2`, `Array.mem`, `Array.for_all`, `Array.memq` etc.

**Comment by sagotch** [comment]
Force pushed with `exists` copied as well.

**Comment by tategakibunko** [comment]
Thank you!

**Pull request merged**
