### PR TITLE
[WIP] Dune build system, documentation and github pages.

### PR DESCRIPTION
**Pull request by sagotch**
Hi!

This PR switch to `dune` build system. Building via `dune` would be cleaner (generated file put in a distinct folder from sources), and easier to use (no need to worry if you rebuilt the test properly before running it). This also fix the install part where jingoo binary was not installed (at least via opam).

I still need to update `examples/Makefile` but I am not sure about what to do about it...

Another good reason to switch to dune is the built-in doc generation. `make doc` will compile doc, and `make gh-pages` will create a `gh-pages` branch with a single commit, containing generated doc. See https://sagotch.github.io/jingoo/

Also, `dune` enable more warnings by default an treat them as errors, so code compiling *should* be less prone to error.

While writing documentation, I feel the need to operate some minor refactoring (essentially: moving some helper to jg_types, reordering functions for documentation purpose).

A possibly breaking change is the removal of `safe` filter, which is now treated in `jg_interp.ml` but is not part of builtin filters. It used to be the identity function, and the effect only take place in `jg_interp` so I think it is correct to treat it as a special, event if I am not sure about this...

Despite the work on documentation, it still is incomplete, but it should be improved with time.

While the `example/Makefile` should be fixed, I opened this PR so you can comment it now, so please let me know what you like or not.

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thank you! I'm also thinking about `dune`, cause everyone uses it. But I'm not understanding it yet well however...

Currently, `make` causes some error in my environment(My version of `dune` is `1.4.0`, and OCaml is `4.07.0`).

Here is my `_build/log`.

```bash
# dune build
# OCAMLPARAM: unset
$ /usr/bin/nproc > /tmp/dunea3e2ad.output 2> /dev/null
$ /home/vagrant/.opam/4.07.0/bin/ocamlc.opt -config > /tmp/dunea0a434.output
$ (cd _build/default && /home/vagrant/.opam/4.07.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I src/.jingoo.objs -I src/.jingoo.objs/.private -I /home/vagrant/.opam/4.07.0/lib/bytes -I /home/vagrant/.opam/4.07.0/lib/re -I /home/vagrant/.opam/4.07.0/lib/seq -I /home/vagrant/.opam/4.07.0/lib/uchar -I /home/vagrant/.opam/4.07.0/lib/uucp -I /home/vagrant/.opam/4.07.0/lib/uutf -no-alias-deps -opaque -open Jingoo -o src/.jingoo.objs/jingoo__Jg_lexer.cmo -c -impl src/jg_lexer.ml)
> File "jg_lexer.mll", line 33, characters 6-82:
> Error (warning 9): the following labels are not bound in this record pattern:
> refill_buff, lex_buffer, lex_buffer_len, lex_abs_pos, lex_start_pos, lex_curr_pos, lex_last_pos, lex_last_action, lex_eof_reached, lex_mem, lex_start_p
> Either bind these labels explicitly or add '; _' to the pattern.
> File "jg_lexer.mll", line 9, characters 2-15:
> Error (warning 33): unused open Jingoo.Jg_types.
[2]
$ (cd _build/default && /home/vagrant/.opam/4.07.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I src/.jingoo.objs -I src/.jingoo.objs/.private -I /home/vagrant/.opam/4.07.0/lib/bytes -I /home/vagrant/.opam/4.07.0/lib/re -I /home/vagrant/.opam/4.07.0/lib/seq -I /home/vagrant/.opam/4.07.0/lib/uchar -I /home/vagrant/.opam/4.07.0/lib/uucp -I /home/vagrant/.opam/4.07.0/lib/uutf -intf-suffix .ml -no-alias-deps -opaque -open Jingoo -o src/.jingoo.objs/jingoo__Jg_parser.cmo -c -impl src/jg_parser.ml)
> File "jg_parser.mly", line 239, characters 2-71:
> Error (warning 50): unattached documentation comment (ignored)
> File "jg_parser.mly", line 240, characters 2-42:
> Error (warning 50): unattached documentation comment (ignored)
> File "jg_parser.mly", line 9, characters 2-15:
> Error (warning 33): unused open Jingoo.Jg_utils.
[2]
$ (cd _build/default && /home/vagrant/.opam/4.07.0/bin/ocamlopt.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -I src/.jingoo.objs -I src/.jingoo.objs/.private -I /home/vagrant/.opam/4.07.0/lib/bytes -I /home/vagrant/.opam/4.07.0/lib/re -I /home/vagrant/.opam/4.07.0/lib/seq -I /home/vagrant/.opam/4.07.0/lib/uchar -I /home/vagrant/.opam/4.07.0/lib/uucp -I /home/vagrant/.opam/4.07.0/lib/uutf -intf-suffix .ml -no-alias-deps -opaque -open Jingoo -o src/.jingoo.objs/jingoo__Jg_parser.cmx -c -impl src/jg_parser.ml)
> File "jg_parser.mly", line 239, characters 2-71:
> Error (warning 50): unattached documentation comment (ignored)
> File "jg_parser.mly", line 240, characters 2-42:
> Error (warning 50): unattached documentation comment (ignored)
> File "jg_parser.mly", line 9, characters 2-15:
> Error (warning 33): unused open Jingoo.Jg_utils.
[2]
```

**Comment by sagotch** [comment]
I think that the error come from intermediate file from previous build system.
`rm src/*.cm* src/jg_lexer.ml src/jg_parser.ml src/jg_parser.mli src/jingoo.a` should be fine.

Alternatively, I updated `.gitignore` so `git clean -df` will take care of removing old build system files (not pushed yet).

Having docs in `docs` folder is fine for me. I used `gh-pages` branch in order to avoid versioning it, but I have no problem with versioning these generated files.

Would you mind if I will add a `.travis.yml` file

**Comment by tategakibunko** [comment]
> rm src/*.cm* src/jg_lexer.ml src/jg_parser.ml src/jg_parser.mli src/jingoo.a should be fine.

Thank you, Now works fine!!

> Would you mind if I will add a .travis.yml file?

Not at all,  except I have to learn new technology lol.

**Comment by tategakibunko** [comment]
After installing `jingoo` via `dune`,  I built `simple` in `example` directory by linking `jingoo` package, I got an error.

```bash
ocamlfind ocamlopt -g -package re,unix,uutf,dynlink,uucp,jingoo -linkpkg -o simple test_data.ml simple.ml
File "simple.ml", line 1:
Error: No implementations provided for the following modules:
         Jg_template referenced from simple.cmx
```
`dune` rename `jg_template.*` to `jingoo__Jg_template.*`, so not found error... maybe.

Hmm, I already merged this PR, but before I'm familiar with `dune` things, can I revert `dune` parts to old Makefile?

**Comment by tategakibunko** [comment]
Oh, I can build `simple.exe` with dune by replacing `open Jg_types` to `open Jingoo.Jg_types`

```
(executable
   (name simple)
   (libraries jingoo))
```

Offcource I have to `install jingoo` before build...

**Comment by sagotch** [comment]
Working on the `example` folder (https://github.com/sagotch/jingoo/tree/dune)

**Comment by tategakibunko** [comment]
Thank you, it's really encouraging.

**Pull request merged**
