### PR TITLE
replace batteries with camomile

### PR DESCRIPTION
**Pull request by seliopou**
The only reason that batteries is a dependency is for the UTF8 support. Equivalent support is provided by camomile. Anybody that has utop installed will have camomile installed as well.

### CODE REVIEW

**Comment by tategakibunko** [comment]
As far as I know, maitainance of camomile has stoppped long time, and author is not willing to continue development.

[https://github.com/yoriyuki/Camomile/issues/12](https://github.com/yoriyuki/Camomile/issues/12)

So I prefer batteries.

**Comment by seliopou** [comment]
Thanks for bringing this to mine and others' attention. Looks like @michipili and @rgrinberg will be taking over maintenance of camomile, so hopefully they'll be able to provide the support you're looking for. Batteries is a big library, so including it just for Unicode support seems like overkill.

**Comment by tategakibunko** [comment]
At the very first code base, jingoo used Camomile, see version 1.2.2.

But some day, camomile version up, and build is failed,  so switched to Extlib.

But one day, user sended Pull Request and says 'Extlib is too old, let's batteries', so I merged it.

Yes I thought it's too large just like you.

And today, 'Batteries is too large, let's camomile!'

OK, maybe now is the time jingoo should use camomile again, but today I pulled it and build from source, it failed again.

It's caused by camlp4o, and it is not included by standard tools of latest OCaml.

So if I want to use camomile again, I have to install camlp4 that is dropped from standard tool set, even if using opam, the process is too wired isn't it?

Offcource if Camomile is easy to install, I want to use it again.

**Comment by seliopou** [comment]
That's quite a compelling narrative that you have there. Had I gone through the same ordeal I'd be wary about switching libraries again.

I'll work on getting rid of the camlp4o dependency in Camomile and check back with you later.

**Comment by tategakibunko** [comment]
> I'll work on getting rid of the camlp4o dependency in Camomile and check back with you later.

Great!

Then I'll switch to camomile again.

**Pull request closed without merging**
