### PR TITLE
Rewrite Jg_utils.escape in a more efficient way.

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by sagotch** [comment]
Few quick benchmarks made with OCaml 4.07.0 showed a wall time of about 60% of original implementation.

**Comment by tategakibunko** [comment]
Thanks!

I noticed that we forgot about `single quote(U+0027)` for escape target, so I added it.

https://github.com/tategakibunko/jingoo/commit/b6cb89735ecf7ac57a0db1854b4e2310ea394e58

**Comment by sagotch** [comment]
Nice.

I just found that https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content recommends to escape `/` characters as well. I don't know what could be wrong not escaping this, since we already escape `>`, but I not an expert. Do you think that we should include `/` to the list?

**Comment by tategakibunko** [comment]
Hmm... I can't understand why `forward slash` must be escaped. Closing tag? But as you said, we already escape `<` and `>`...

Most WAF treat just 5 characters as escape target(&,<, >, ", '), php, tornado, rails etc.

But there is some resource that is saying **Escaping &, <, >, ", ', `, , !, @, $, %, (, ), =, +, {, }, [, and ] is almost enough**.

https://wonko.com/post/html-escaping

But they are for bugs of old Internet Explore, and for `unquoted html attribute` like

```html
<a name=unquotedName>
<a name='quotedName'>
```

If template user set user input to the position of `unquotedName`, like 

```
<!-- name is unquoted! -->
<a name={{name}}>danger</a>
```

then it will be malicious... but I don't know that html allows unquoted attribute until I read this article.

But `forward slash` is still not included in this article.

So I don't think we have to escape `forward slash`.

At the same time, if we escape all, it will be endless..., so I think 5 characters(&,<,>,",') are enough.

**Comment by sagotch** [comment]
Agreed.

**Pull request merged**
