### PR TITLE
Implemented jg_batch for arrays.

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thank you! But don't forget to write unit test if you add something new to runtime.

And I've just added unit-test for this PR, it fails. Please check it out.

```ocaml
```

**Comment by sagotch** [comment]
Sorry about that, I really pushed it too quickly...

**Comment by sagotch** [comment]
I added a basic printer for debuging test and rewrote some of them to use this printer.

Ad you can see, the fix for `jg_batch` is the first commit only. Feel free to cherry-pick if you do not want the rest.

**Comment by tategakibunko** [comment]
Thank you! Now error message for unit test is far more better!!

And my bad, my unit test code was not enough, so I've added one more test pattern(If `fill_with` keyword is not given, final row is shrinked to `array_length mod slice_count`).

So I've added tiny patch to `jg_batch`, and finally I've learned `Array.init` and `Array.sub` lol.

**Pull request merged**
