### PR TITLE
Added ast_mapper in order to implement optimization passes

### PR DESCRIPTION
**Pull request by sagotch**
I pre-load my templates and I need to inline `include` directive in order to avoid unnecessary file opening and parsing at runtime.

I needed some AST mapper in order to implement this feature.

I planned to add some optimization step such as dead code elimination or macro inlining.

### CODE REVIEW

**Comment by tategakibunko** [comment]
By this PR, we can get in-memory template. It's cool!!

But you replaced include statement to block-statement with null name.

It's not formal use-case of block statement, and other developer may confuse.

So how about adding new statement `InlinedStatement(stmts)` to `Jg_types.statement` just for internal inlining purpose?

```ocaml
| IncludeStatement(file)-> 
  let stmts = ast_from_file env self file in 
  InlinedStatement(stmts)
| InlinedStatement(stmts) -> stmts
```

And if there is `ast_from_string` too, I'll be so happy!! :)

**Comment by sagotch** [comment]
I first created a version with a new statement type, but I found that an unnamed statements blocks will suit well because it actually is what is it, a block of statements with no name.

But you are right, block statements in jinja2 is meant to be named so it can be replaced. I will fix this. And also add the ast_from_string thing.

**Comment by tategakibunko** [comment]
> EDIT: I would rather prefer to use a more generic name than inlinedStatement so I may be used in some other case. What about the simple `Statements of ast` constructor ?

OK, no problem.

**Comment by sagotch** [comment]
I just saw that my PR include whitespace modifications, I should fix this, sorry.

**Comment by tategakibunko** [comment]
OK, I'll wait.

Currently about 30% of unit-test fails, and extends statement in `cheatsheet.tmpl` doesn't work well.

When I tested, all tags defined in `base.tmpl` is not outputted, and contents of `head`, `nav` block appear AFTER main block, so alignment order is not correct.

It seems it erases original template structure in `base.tmpl`, and each blocks are aligned in reverse order.

FYI, If `base.tmpl` is defined like this..

```jinja2
{# base.tmpl #}
<html>
  <body>
    <main>{% block main %}{% endblock %}</main>
    <nav>{% block nav %}{% endblock %}</nav>
    <footer>{% block footer %}{% endblock %}</footer>
  </body>
</html>
```

And when we 'use'	this template as parent	structure like this...

```jinja2
{% extends "base.tmpl" %}
{% block main %} this is main {% endblock %}
{% block nav %} this is	nav {% endblock %}
{% block footer %} this	is footer {% endblock %}
```

Then correct output is

```html
<html>
  <body>
    <main> this	is main	</main>
    <nav> this is nav </nav>
    <footer> this is footer </footer>
  </body>
</html>
```

But currently, this PR outputs like this.

```html
this is main
this is footer
this is nav
```

**Comment by sagotch** [comment]
Ah yes, I forgot that I was iterating on a reversed ast, thanks.

**Comment by sagotch** [comment]
Ah yes, nesting ast in a `Statements` should indeed hide the block from the replacement loop...

And the inline_include optimisation would have the same problem...

**Comment by sagotch** [comment]
This should work now. But it still is poorly tested.

Also, I do not know what you think about the last two commits (refactoring using the ast_mapper). Do you like it or not? I think they are a good way to do things.

**Comment by tategakibunko** [comment]
I've tested now, and seems OK! Now I'm going to test deeper.

>Also, I do not know what you think about the last two commits (refactoring using the ast_mapper). Do you like it or not? I think they are a good way to do things.

Offcource I love it!! It will give us more flexible way to operate ast.

Before this PR, we have only `string -> string` interface about template. But now we gain `string -> ast` and `ast -> string`. And by the `ast_mapper`, we can override parsing way for each statement and expression. It's solid refactoring.

In addition, there is issue #42  and in-memory template must be supported to implement loader like jinja2.

But this PR is a bit large for me, so it takes time to investigate^^;

**Pull request merged**
