### PR TITLE
Add 'map' filter and look for a __str__ property when trying to print an object.

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thanks!

But following code did not show anything.

```jinja2
{% for name in map(persons, attribute="name") %} {{name}} {% endfor %}
```

So I've modified your code a little(removed `filter` argument from `jg_map` and wrap it  by `func_args1`).

But if it's not what you indended to do, feel free to point out.

**Comment by tategakibunko** [comment]
Sorry, `filter` argument is used like this?

```jinja2
{% for name in map(persons, "lower", attribute="name") %} {{ name }} {% endfor %}
```

Then `func_args2` is correct, my bad.

**Comment by sagotch** [comment]
I would write 

```
{% for name in persons | map (attribute="name") %} {{ name }} {% endfor %}
```

This first version only works with attributes indeed, not functions, but I add function support soon enough.

**Comment by tategakibunko** [comment]
Thanks for answer!

Lacking arguments(via filter) become `Tnull` automatically, I remember now.

**Comment by tategakibunko** [comment]
Today I noticed that following code in `cheatsheet.jingoo` displays nothing.

```jinja2
{% for name in persons | map(attribute="name") %} {{name}} {% endfor %}
```

I was careless. Lacking argument is not padded by `Tnull`, it returns curried function.

So `persons | map(attribute="name")` just returns curried function`filter -> kwargs -> tvalue` because `jg_map` is `func_arg2`, that is, `list -> filter -> kwargs -> tvalue`

So currently, we have to set `filter` argument as `null` to use `map`.

```jinja2
{% for name in map(persons, null, attribute="name") %} {{name}} {% endfor %}
```

And if we write this code like this, it fails,

```jinja2
{% for name in persons | map(null, attribute="name") %} {{name}} {% endfor %}
```

because first argument of `map` must be `persons` that is `Tlist` or `Tarray`.

**Comment by tategakibunko** [comment]
> Should it be jg_map ctx filter list kwargs instead of jg_map ctx list filter kwargs?

Umm... then `kwargs`(attribute="name") become `list`, and `list`(persons) become `kwargs`.

It may be hard to use `func_args2` at filter positoin in our current jingoo design...

**Comment by tategakibunko** [comment]
Currentry Tfun is defined by `Tfun of kwargs -> args -> tvalue`.

I wanna replace this to `Tfun of (?kwargs:kwargs -> args -> tvalue)` (make `kwargs` optional).

**Comment by tategakibunko** [comment]
Fixed. I've updated `Tfun`(and argument order of `jg_map` as pointed out).

Now we can use curried function with keyword arguments.

```jinja2
{# normal function call #}
{% for name in map(null, persons, attribute="name") %} {{name}} {% endfor %}

{# curried Tfun with keyword arguments #}
{% for name in persons | map(null, attribute="name") %} {{name}} {% endfor %}
```

**Comment by sagotch** [comment]
Nice!

But isn't it strange to have `null` before `persons`. I would say that one would expect person to be first or last argument?

**Comment by tategakibunko** [comment]
> But isn't it strange to have null before persons. I would say that one would expect person to be first or last argument?

Ahh, it was my bad example code, I should have written like this.

```jinja2
{% for name in persons | map(attribute="name", null) %} {{ name }} {% endfor %}
```

Both code works.

Offcource `persons` should be last argument of `jg_map` because it's passed to curried function of `map`.

**Pull request merged**
