### PR TITLE
Improved UTF8 support.

### PR DESCRIPTION
**Pull request by sagotch**
Used `uutf` and `uucp` (new dependency but that should be okay, this is small lib meant to work with `uutf`, which is already a dependency) in order to support case mapping for utf8 string.

`String` modules function are deprecated and case folding is totally broken on unicode input. (See https://caml.inria.fr/mantis/view.php?id=5732)

WARNING: breaking fix !
I assumed that `jg_title` was broken, since it was a `capitalize` with extra space removal. Since multiple spaces are like on space for web browser, removing or adding extra spaces should not change the display (unless `pre` tag, but this is not likely what you want to do with a title). So title was basically implemented as `capitalize`.
The new version should be closer than what you expect when using titlecase (every word begin with uppercase, and the rest is lowercase), and follows what jinja2 do http://jinja.pocoo.org/docs/2.10/templates/#title

Also, I was tempted to replace your split function using `Jg_utils.UTF8.split`, but you would loose the regex support, (not strings delimiters, but real regex). Same comment for the `replace` function.

### CODE REVIEW

**Comment by tategakibunko** [comment]
Thanks for fixing my bugs!

Today I've reviewed unicode things, and I noticed that

- `Pcre.regexp "\\s" ~flags:[UTF8]` doesn't match `\u3000`! lol
-  `uucp` failed to install in my environment...?
```bash
opam install uucp
Your request can't be satisfied:
  - utop is not available because your system doesn't comply with ocaml-version >= "4.02.3" & ocaml-version < "4.07.0".
```

- But in `uucp`, there is  `Uucp.White.is_white_space`, and it seems very usefull.

By the way, there are so many kind of space characters in unicode, as far as I know, these are 26 kinds of spaces.

```
U+0009-U+000d, U+0020,
U+0085, U+00a0, U+1680, U+180e, 
U+2000-U+200a,
U+2028-U+2029,
U+202f, U+205f, U+3000
```

In this PR, `U+3000` is supported in  `is_space`, but it's not enough.

So I want to test `Uccp.White.is_white_space` but I'm not familiar with Uucp module, and before that, I can't install `uucp` lol.

**Comment by sagotch** [comment]
Did you try after `opam update` ? It is written that it should be available with `"ocaml" {>= "4.01.0"}`

```
$ opam info uucp

=-=- uucp: information on all versions =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
name                   uucp
all-installed-versions 11.0.0 [4.05.0]
all-versions           0.9.0  0.9.1  1.0.0  1.1.0  2.0.0  10.0.0  10.0.1
                       11.0.0

=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
version       11.0.0
repository    default
url.src:      http://erratique.ch/software/uucp/releases/uucp-11.0.0.tbz
url.checksum: md5=38565e80bf92f93b4ced73368038baee
homepage:     http://erratique.ch/software/uucp
bug-reports:  https://github.com/dbuenzli/uucp/issues
dev-repo:     git+http://erratique.ch/repos/uucp.git
authors:      "Daniel Bünzli <daniel.buenzl i@erratique.ch>"
              "David Kaloper Meršinjak <david@numm.org>"
maintainer:   Daniel Bünzli <daniel.buenzl i@erratique.ch>
license:      ISC
tags:         "unicode" "text" "character" "org:erratique"
depends:      "ocaml" {>= "4.01.0"}
              "ocamlfind" {build}
              "ocamlbuild" {build}
              "topkg" {build}
              "uchar"
              "uucd" {with-test}
              "uunf" {with-test}
              "uutf" {with-test}
depopts:      "uunf" "uutf" "cmdliner"
conflicts:    "uutf" {< "1.0.1"} "cmdliner" {< "1.0.0"}
synopsis      Unicode character properties for OCaml
description
          Uucp is an OCaml library providing efficient access to a selection of
          character properties of the [Unicode character database][1].
          Uucp is independent from any Unicode text data structure and has no
          dependencies. It is distributed under the ISC license.
          [1]: http://www.unicode.org/reports/tr44/
```

I did not know about `Uucp.White.is_white_space` (`Case` module in actually the only one I knew)

**Comment by tategakibunko** [comment]
Thanks for advice!  Now I've installed `uucp` successfully.

**Comment by sagotch** [comment]
I tried in `4.02.1` and it should work...

```
opam switch create 4.02.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocaml-base-compiler.4.02.1] downloaded from cache at https://opam.ocaml.org/2.0/cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
∗  installed ocaml-base-compiler.4.02.1
∗  installed ocaml.4.02.1
∗  installed base-ocamlbuild.base
Done.
# Run eval $(opam env) to update the current shell environment
```

```
opam install uucp
The following actions will be performed:
  ∗  install ocamlbuild 0      [required by uucp]
  ∗  install conf-m4    1      [required by ocamlfind]
  ∗  install result     1.2    [required by topkg]
  ∗  install uchar      0.0.2  [required by uucp]
  ∗  install ocamlfind  1.8.0  [required by uucp]
  ∗  install topkg      0.9.1  [required by uucp]
  ∗  install uucp       11.0.0 
===== ∗  7 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlfind.1.8.0] found in cache
[topkg.0.9.1] found in cache
[uchar.0.0.2] found in cache
[uucp.11.0.0] found in cache
[result.1.2] downloaded from cache at https://opam.ocaml.org/2.0/cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed ocamlbuild.0
∗  installed conf-m4.1
∗  installed result.1.2
∗  installed uchar.0.0.2
∗  installed ocamlfind.1.8.0
∗  installed topkg.0.9.1
∗  installed uucp.11.0.0
Done.
# Run eval $(opam env) to update the current shell environment
```

**Comment by tategakibunko** [comment]
I don't remember what I pinned before, but after `opam upgrade` and `opam update`, it works well.

And I merged this PR, because now I've noticed that `Pcre.regexp "\\s" ~flags:[UTF8]` doen't work as I expected. This PR is far more better.

**Comment by tategakibunko** [comment]
I tried `Uucp.White.is_white_space` and it's awesome!

```ocaml
let check_white i =
  let uc = Uchar.of_int i in
  print_endline (Printf.sprintf "%x is_whilte_space = %b" i (Uucp.White.is_white_space uc))

let () =
  List.iter check_white [
    0x0009; 0x000a; 0x000b; 0x000c; 0x000d;
    0x0020; 0x0085; 0x00a0; 0x1680; 0x180e; (** MONGOLIAN VOWEL SEPARATOR *)
    0x2000; 0x2001; 0x2002; 0x2003; 0x2004;
    0x2005; 0x2006; 0x2007; 0x2008; 0x2009;
    0x200a; 0x2028; 0x2029; 0x202f; 0x205f;
    0x3000;
  ]
```

Result is

```bash
9 is_whilte_space = true
a is_whilte_space = true
b is_whilte_space = true
c is_whilte_space = true
d is_whilte_space = true
20 is_whilte_space = true
85 is_whilte_space = true
a0 is_whilte_space = true
1680 is_whilte_space = true
180e is_whilte_space = false
2000 is_whilte_space = true
2001 is_whilte_space = true
2002 is_whilte_space = true
2003 is_whilte_space = true
2004 is_whilte_space = true
2005 is_whilte_space = true
2006 is_whilte_space = true
2007 is_whilte_space = true
2008 is_whilte_space = true
2009 is_whilte_space = true
200a is_whilte_space = true
2028 is_whilte_space = true
2029 is_whilte_space = true
202f is_whilte_space = true
205f is_whilte_space = true
3000 is_whilte_space = true
```

Without `U+180E`(MONGOLIAN VOWEL SEPARATOR), all kinds of international spaces are properly recognized.

**Comment by sagotch** [comment]
I do not really know what is going on, but *The Mongolian Vowel Separator (U+180E) has oscillated between the Cf and Zs categories a couple of times* https://codeblog.jonskeet.uk/2014/12/01/when-is-an-identifier-not-an-identifier-attack-of-the-mongolian-vowel-separator/

This should probably be an issue opened in https://github.com/dbuenzli/uucp/issues, but I am not sure yet about this.

**Comment by tategakibunko** [comment]
>In Unicode 6.3.0 it was then moved back to the Cf category.

Thanks for information!

It seems my knowledge was too old. Currently `U+180e` is included in `Cf` category.

http://www.fileformat.info/info/unicode/char/180e/index.htm

So `uucp` is correct!

**Pull request merged**
