### PR TITLE
Bench: used benchmark library and avoid result being polluted by file opening time.

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by tategakibunko** [comment]
Unfortunatelly, it seems `benchmark` package requires ocaml >= 4.02.3(jingoo supports ocaml >= 4.02.0).

But as you pointed out, unnecessary file openning is bad.

So I want to just replace `from_file` to `from_string` in old benchmark code.

**Comment by sagotch** [comment]
Also, your count variable is not used.

**Comment by sagotch** [comment]
And if you are interested in benchmark (which provide user and cpu times), you can install `benchmark.1.4` which works as well.

**Comment by tategakibunko** [comment]
OK, I'll close PR this time... but

> Also, your count variable is not used.

Hmm.., what is this meaning?

When I tried `./bench -count 1000`. time is 0.793929, and `-count 10000` then  7.566693.

**Comment by tategakibunko** [comment]
So I've replaced `from_template` to `from_string`.

https://github.com/tategakibunko/jingoo/commit/89460e22ef193f1fd110446a0a6cbcebbf24a2e3

I don't know what was problem but I think `count` variable was just used and worked properly.

If it's my misunderstanding of something, feel free to point out.

**Comment by sagotch** [comment]
I read to quickly the diff, and thought that first loop was the place where count should have been used, but it is in the second loop, sorry about that.

**Pull request closed without merging**
