### PR TITLE
Fixes for PR#81

### PR DESCRIPTION
**Pull request by sagotch**
Sorry about that, I forgot to push these commits before telling you that merge was ok...

### CODE REVIEW

**Comment by tategakibunko** [comment]
It's okay but there is some questions about following code.

```ocaml
begin
    try 0 = unbox_int @@ jg_apply (jg_obj_lookup left "__eq__") [ left ; right ]
    with _ -> jg_obj_eq_eq left right
 end
```

1. Is there any documentation about `__eq__`?
2. Is this special member `__eq__` is  used to compare object by some primary id or something like that?

**Comment by sagotch** [comment]
I added this commit this morning, and probably should not push it to master branch...

`__eq__` should return a boolean, not an int, it is a wrong copy/paste from what is done with `__compare__`.

It is useful for instance for comparing objects using `Tpat` constructor. Also, it may allow to define shortcut for object comparison (with a primary id of something like that indeed).

But it definitely should not be wrapped in a int...

**Comment by sagotch** [comment]
And documentation is missing. I should write a section about these special fields `__str__`, `__eq__` and `__compare__`. I'll do.

**Comment by tategakibunko** [comment]
Thanks for answer!

I also think it's nice for shortcut comparison about complex object.

**Pull request merged**
