### PR TITLE
Support += operator for 'set' statement.

### PR DESCRIPTION
**Pull request by sagotch**
Fix https://github.com/tategakibunko/jingoo/issues/91

### CODE REVIEW

**Comment by tategakibunko** [comment]
Could you add `-=` operator in this PR?

Of course I can copy your code, and add some update for it, but maybe it's redundant and not a good manner.

**Comment by sagotch** [comment]
<strike>
I did not add `-=` operator because it would only have sens for numbers. `+=` also work for string concatenation or list appending (and basically could work for any types by rendering as string) as long as `jg_plus` support it.

Isn't `{% set += - 1 %}` good enough?
</strike>

That being said, there is no good reason to support only `jg_plus` and not `jg_minus`, so yes, I will add `-=` support.

**Comment by tategakibunko** [comment]
Thank you!

But I can't merge branch `+=`, any idea?

```bash
git checkout -b geneanet-+= master
git pull https://github.com/geneanet/jingoo.git +=
fatal: Couldn't find remote ref =
```

**Comment by tategakibunko** [comment]
Sorry, I can merge by

```
git pull https://github.com/geneanet/jingoo.git ++=
```

**Comment by sagotch** [comment]
Sorry about that branch name ^^

**Comment by tategakibunko** [comment]
I forgot about `%=` operator, so added it.

https://github.com/tategakibunko/jingoo/commit/1fbcdcbc2f9680e677589bb692a18cdcb21c239c

**Pull request merged**
